apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata: 
  name: vps-demo
spec: 
  targetRef: 
    apiVersion: "apps/v1"
    kind: Deployment
    name: autoscale-tester
updatePolicy:
  updateMode: "Off"
resourcePolicy:
  containerPolicies:
    - containerName: autoscale-tester
      minAllowed:
        cpu: "500m"
        memory: "500Mi"
      maxAllowed:
        cpu: "4"
        memory: "8Gi"
