apiVersion: v1
kind: ConfigMap
metadata:
  name: kul-for-files
data: 
  dev.properties: |
    dev1=value1
    dev2=value2
    dev3=value3
  qa.properties: |
    qa1=value1
    qa2=value2
    qa3=value3
  prod.properties: |
    prod1=value1
    prod2=value2
    prod3=value3