apiVersion: batch/v1beta1
kind: CronJob

metadata:
  name: cj-demo
  labels: 
    day: "6"

spec:
  schedule: "*/1 * * * *"
  successfulJobHistoryLimit: 2
  failedJobHistoryLimit: 2
  jobTemplate:
    spec:
      template: 
        spec: 
          containers:
            - name: cj-demo
              image: busybox
              args:
                - /bin/sh
                - -c
                - date && echo Hello from k8s Cluster
          restartPolicy: OnFailure
