apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-demo
  labels: 
    name: ds-demo
spec:
  selector:
    matchLabels:
      name: ds-demo
  template: 
    metadata:
      labels:
        name: ds-demo
    spec:
      tolerations:
        - key: "taint"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
          
      containers:
        - name: httpd
          image: httpd
