apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kul
  annotations: 
    repo: https://github.com/kul-infosys/kubernetes-advanced.git
    maintainer: Kulbhushan Mayer
  labels: 
    day: "3"
    client: Infy
    name: httpd
    type: deployment
  namespace: kul
spec: 
  template:
    metadata:
      labels:  
        day: "3"
        client: Infy
        name: httpd
    spec: 
      tolerations:
        - key: taint
          operator: Equal
          value: true
          effect: NoSchedule
      containers:
        - name: httpd
          image: httpd
      nodeSelector:
        env: perf
  selector:
    matchLabels:  
      day: "3"
      client: Infy
      name: httpd
  replicas: 4
        