apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kul
  annotations: 
    repo: https://github.com/kul-infosys/kubernetes-advanced.git
    maintainer: Kulbhushan Mayer
  labels: 
    day: "3"
    client: Infy
    name: httpd
    type: deployment
  namespace: kul
spec: 
  template:
    metadata:
      labels:  
        day: "3"
        client: Infy
        name: httpd
    spec: 
      tolerations:
        - key: "taint"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: httpd
          image: httpd

          # Adding Resrouce Quota to ensure minimum availablity of resources to Schedule the Pod on stable node and post scheduling it should not consume extra resource because some leakage or bug

          resources:
            requests: 
              memory: "64Mi"
              cpu: "250m"
            limits: 
              memory: "128Mi"
              cpu: "500m"

          # Adding Environment Variables
          env: 
            - name: DB_USER
              value: mydbuser
            - name: DB_Sever
              value: myserver.com

          # Using Envrionment Variable with ConfigMaps
          envFrom:
            - configMapRef:
                name: kul
          
          # Added to read configMaps values as files inside the container
          volumeMounts:
            - name: env-properties
              mountPath: "/env"
              readOnly: true

      nodeSelector:
        env: perf
      volumes:
        - name: env-properties
          configMap: 
            name: kul-for-files
            items:
              - key: dev.properties
                path: dev
              - key: qa.properties
                path: qa
              - key: prod.properties
                path: prod
  selector:
    matchLabels:  
      day: "3"
      client: Infy
      name: httpd
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
---
apiVersion: v1
kind: Service
metadata: 
  name: kul
spec: 
  type: NodePort #Other Options #LoadBalancer #ClusterIP
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31000 # Should be in range of 30000-32767
      name: access-apache
    - protocol: TCP
      port: 8080
      nodePort: 31001
      name: dummy-ort
  selector: 
    day: "3"
    client: Infy
    name: httpd
    