apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    probe: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
      - /bin/sh
      - -c
      - touch /tmp/liveness; sleep 30; rm -rf /tmp/liveness; sleep 1800
    livenessProbe:
      exec: 
        command: 
          - cat 
          - /tmp/liveness
      initialDelaySeconds: 5
      periodSeconds: 30
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp-socket
  labels:
    probe: liveness-tcp-socket
spec:
  containers:
  - name: liveness-tcp-socket
    image: kulbhushanmayer/tomcat:9.0.38
    ports:
      - containerPort: 8080
    readinessProbe:
      tcpSocket: 
        port: 8080
      initialDelaySeconds: 20
      periodSeconds: 30
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 20
