apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: multi-container
spec: 
  volumes:
    - name: htdocs
      emptyDir: {}
  containers:
  - name: main
    image: httpd
    volumeMounts:
      - name: htdocs
        mountPath: /usr/local/apache2/htdocs
    readinessProbe:
      tcpSocket: 
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 30
      
  - name: second-container
    image: k8s.gcr.io/busybox
    volumeMounts:
      - name: htdocs
        mountPath: /tmp
    args:
      - /bin/sh
      - -c
      - echo <br>`date`</br> >> /tmp/index.html && sleep 5 && echo <br>`date`</br> >> /tmp/index.html && sleep 5
