apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: multi-container
spec: 
  volumes:
    - name: htdocs
      emptyDir: {}
  containers:
  - name: main
    image: httpd
    volumeMounts:
      - name: htdocs
        mountPath: /usr/local/apache2/htdocs
    readinessProbe:
      tcpSocket: 
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 30
      
  - name: second-container
    image: debian
    volumeMounts:
      - name: htdocs
        mountPath: /tmp
    command: ["/bin/sh", "-c"]
    args: 
      - date >> /tmp/index.html && sleep 5
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    name: multi-container
spec:
  type: NodePort
  selector:
    name: multi-container
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    name: apache
