apiVersion: certificate.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: deployment-user
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRWNUQ0NBbGtDQVFBd0xERVlNQllHQTFVRUF3d1BaR1Z3Ykc5NWJXVnVkQzExYzJWeU1SQXdEZ1lEVlFRSwp
EQWRKYm1admMzbHpNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXI4SjV5QWlFClJFWnpjZ09ZVVRyTmpGdVo5WDlRbXdMRlJrbVNlbGhLWVpFSV
orelpUTzF0bGR2ZjZkNzMwZmZPUDJwL0tPNTkKVm1TeFMwYjF4alJsakJCbWg3WjRnOEhObWxpOVZLeVhMUktUUWs0QWNqM3ZWWjc1T1RvMUNXejZVRVRSTXAvYQpkQ040VWZDc
2xWUml4ZnNHRS9pa3hhM3hZRWtqU3pUcVBsRGdRSVZHTENvbHBCY25GQlJLUG9IYUxyempNcmRnCmRuSzE1Y0VhTnM2dnZ5czh2NElteWtibjhET04zNWhOWU5QOXFLUkl2RXJQ
OWhPQ201SkxOdi9mRUZSV2J3czcKRFN6T1UzUzkrR0NUcExjUXltNjRLdlA3OUFtdjNKUUdmeGNZVHNqQko1emNHREo0Q0NydW9XblJGS3U1cjN6TApOem5yY0VqSlhkUERhU0d
EemkzQUtUSUY3M1FpSmV4eGMrY3R1aUNHSS96SGdaMXhEdTZhMFZ1RGg3TkxGNldrCmpFSDFqbnlvRlltRG42MG91dEJmcXpPL2VZWUJmWDdDTUc1SmlsOGt5a0RFWStRMVNTNn
FiL0VkZW9xWnNMUDkKUzRNdzgzdnZFcWRFcEJGR0Q5Tk4zOGVHTTNSdmFuRHdmVmkwdFhWZGlLZSthb1RLcmdoQWt2TTByU2NRNWJVdApFenBGaXc1a1N5Nm9rT3N4UTIvOWVTd
Dh6RVRMZmY3elAvVnpvTHdUbWNWdlpmQTBEMlpIU0lha05BQ2Nva3EyCmZoTmo2dVluZnQ3eENLakJnUGpHeXRueGtES3pvb3lvTmFsWktpd1ZpVnZJSTZ4cGNzRnFQbTVRMDIy
bkU3c0sKeXkyVWs3MG9SSmJsbXVZcFVDcGZvbjE4U3FwTkMwME1aNHNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElDQVFCREFqSmtUdG9Pa3V3azA1b3JNTDF5c3h
mYWlkZVEyV2dnQ2NFZkUvMkhoWk9NTWxzbU56K3lidER3Ck5xektRcVdDa1RsT1FoY3grdzFwT2pCeFhRak1VUFZPcU1WRTZqRXJlWU5JcytFekVqaTBZbzc0ZkVTUG92Z1AKeG
9OSmE1c1Ztei9icFlOeVdjWWNSaVpETHVTSjJEUHZHb2FFeFh1MURaa2NpZk1WSlU5bk4wZ2FzVVFDRjJ1ZApleFNtR3hwTHdIWlI5ZDd2N2M0Ti9WeHNhWHYzTDNpZHZHVkJYe
mNkZUZBUGF5NTJHNGpXMlFLOFAvbFYrSkVkCm1EZXpJMHpFdzNjMHczYy9JWUJzNEtoU1FqTTBrZEZGcVJLclJYTHRsUjljdkk1MFE5V083bnlRbHhmNllFU3YKOHBiLy9OVWU4
KzZCVklialFlYmpUNHd2Rzk4VkZCR3FjckFwazFlVENKMk9zREorUTlYL2RNdGJhTThCamIzMwpHVGluNUxhNlBISEJLMWwybmJidzZLNmJxZVVuTlAwMVJIUmk2UFpMTHFnejh
GejJRQWRwd0g5aDBBUGRKSGQwCm9penJ3TmZEZWUwdWRsQ2tKN2FROXpZZ05GNzJyRmwzZXRqL05rUEZBSThoOFJ5VFVnKzNLeHVGM2FZRGEwQkEKQ1pubmdpZ0dLOTkwMUVScm
9XanI2dlRoTmZ2UWpHWjZZVmpTeG42dGYxVTRudWZWc0VTZ2ZHd0pPdFY0eUJQOAo3VWppcFk4eXJmMTJSdnJBZWhqcFNwYVM2NndpRjkvODRzREx3TmlFRW92SlN2SVYrQklYS
3Rzb0VDUGRLWWxlCndiZmpHTHQzVFRUNHlXWC9RckhURGk3RVg5Tm1QVW12M1JMQWdNbWs5TmRuQSt2bk13PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==

usages:
  - client auth